name: CI

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint-build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@master
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install packages
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test
